### ISSUE TITLE
No sample works on my Ubuntu 12.04 box

### ISSUE THREAD

**Issue by mahiuchun** [g-truc/ogl-samples#17]
I know my GPU is old. The compilation stops at some gl-410-\* file; I assume that it is because I only have OpenGL 3.3 

$ glxinfo | grep -i opengl
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce G 103M/PCIe/SSE2
OpenGL version string: 3.3.0 NVIDIA 319.32
OpenGL shading language version string: 3.30 NVIDIA via Cg compiler
OpenGL extensions:

I thought that I can get 300, 320, 330 things work at least. However, it is not the case and many programs ends with "(0) : error C5145: must write to gl_Position".
