### ISSUE TITLE
problem compiling with glfw 3.0.3. v3.0.4 works

### ISSUE THREAD

**Issue by fzzy** [g-truc/ogl-samples#45]
Can't compile the samples with glfw 3.0.3 in Linux.
I can only get it working with 3.0.4.

```
cmake ..
```
```
[fzzy@stacker ~/ogl-samples-4.5.0.0/external/glfw-3.0.3/build]$ make
Scanning dependencies of target glfw
[  2%] Building C object src/CMakeFiles/glfw.dir/clipboard.c.o
In file included from /home/fzzy/ogl-samples-4.5.0.0/external/glfw-3.0.3/src/internal.h:67:0,
                 from /home/fzzy/ogl-samples-4.5.0.0/external/glfw-3.0.3/src/clipboard.c:27:
/home/fzzy/ogl-samples-4.5.0.0/external/glfw-3.0.3/src/win32_platform.h:65:21: fatal error: windows.h: No such file or directory
 #include <windows.h>
                     ^
compilation terminated.
src/CMakeFiles/glfw.dir/build.make:54: recipe for target 'src/CMakeFiles/glfw.dir/clipboard.c.o' failed
make[2]: *** [src/CMakeFiles/glfw.dir/clipboard.c.o] Error 1
CMakeFiles/Makefile2:106: recipe for target 'src/CMakeFiles/glfw.dir/all' failed
make[1]: *** [src/CMakeFiles/glfw.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by Groovounet** [comment]
The OpenGL samples have been updated to GLFW 3.1.1 which should resolve this issue.
